# Generated by Django 5.2.4 on 2025-08-18 15:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DRSApp', '0003_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='upload_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
