# Generated by Django 5.2.4 on 2025-08-18 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DRSApp', '0004_upload_upload_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='file_type',
            field=models.CharField(blank=True, default='audio', max_length=20),
        ),
        migrations.AddField(
            model_name='upload',
            name='status',
            field=models.CharField(default='pending', max_length=30),
        ),
    ]
