# Generated by Django 5.2.4 on 2025-09-01 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DRSApp', '0005_upload_file_type_upload_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='topic',
            field=models.CharField(blank=True, default='test', max_length=50, null=True),
        ),
    ]
