# Generated by Django 5.2.4 on 2025-10-07 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DRSApp', '0006_upload_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=200)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField(blank=True, max_length=250)),
            ],
        ),
    ]
